### PR TITLE
Alter final screen's behaviour [SA-10194]

### PR DESCRIPTION
**Pull request by stevechan**
This changes the default Microsoft Teams app to redirect to /api/teams.php with two querystring params: the schoolbox domain and the meeting url. This allows us to return the meetingUrl's value to our own domain, and therefore inspect iframe contents to extract it and send it to the cke dialog.

Screenshot from 2020-03-30 20-00-02

### CODE REVIEW

**Comment by stevechan** [comment]
also, first.

**Comment by armatronic** [comment]
Merge conflict? how is this possible?

**Comment by stevechan** [comment]
Don't know. It wasn't conflicting yesterday when I made it.

**Comment by jleckie** [comment]
Cause I already pushed this change.. read the slack plz..

**Comment by armatronic** [comment]
I guess this can be closed then :man_shrugging:

**Pull request closed without merging**
